import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  item: {
    flex: 1,
    width: '100%',
    height: 200,
  },
  imageStyle: {
    alignSelf: 'center',
    width: '90%',
    height: 150,
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#ddd',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  nameStyle: {
    marginLeft: 10,
    color: '#0a0a0a',
    fontSize: 14,
  },
  priceStyle: {
    marginLeft: 10,
    color: '#0a0a0a',
    fontSize: 14,
  },
  addViewStyle: {
    marginTop: 10,
    width: '60%',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },

  plusMinusViewStyle: {
    marginTop: 10,
    width: '70%',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },
  plusView: {alignItems: 'center', justifyContent: 'center'},

  addTextStyle: {textAlign: 'center', fontSize: 18, color: '#2e8d0c'},
  plusTextStyle: {fontSize: 30, color: '#696969'},
  minusTextStyle: {fontSize: 25, color: '#696969'},
  rowViewStyle: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',

    margin: 20,
    flex: 1,
    width: '90%',
  },
  animateViewStyle: {
    flex: 1,
    width: '90%',
  },
  cartRowViewStyle: {
    flexDirection: 'row',
    flex: 1,
    width: '80%',
  },

  cartImageStyle: {
    marginTop:10,
    marginLeft: 20,
    alignSelf: 'center',
    width: 60,
    height: 60,
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#ddd',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  cartPlusMinusViewStyle: {
    marginRight:10,
    alignSelf: 'center',
    width: '30%',
    borderRadius: 20,
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },
});

export default styles;
