export const LOGIN_API_CALL = 'LOGIN_API_CALL'
export const GET_USER_API_CALL = 'GET_USER_API_CALL'
export const USER_PUNCH_API_CALL = 'USER_PUNCH_API_CALL'
export const CHANGE_PASSWORD_API_CALL = 'CHANGE_PASSWORD_API_CALL'
export const SET_USER_INFO = 'SET_USET_INFO'
export const SET_USER_PUNCH = 'SET_USET_PUNCH'
export const SET_LOGIN_TOKEN = 'SET_LOGIN_TOKEN'
export const SET_SELECTED_DRAWER_ROW = 'SET_SELECTED_DRAWER_ROW'
export const FETCH_USER_INFO = 'FETCH_USER_INFO'



