import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  item: {
    flex: 1,
    width: '100%',
    height: 200,
  },
  imageStyle: {
    alignSelf: 'center',
    width: '90%',
    height: 150,
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#ddd',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  nameStyle: {
    marginTop: 10,
    textAlign: 'center',
    color: '#0a0a0a',
    fontSize: 16,
  },
  headerView:{
    alignItems: 'center',
    backgroundColor: '#00BCD4',
    height: 60,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cartImage: {
    marginTop: 5,
    alignSelf: 'center',
    marginRight: 20,
    justifyContent: 'center',
    width: 35,
    height: 35,
    tintColor: '#FFFFFF',
  },
  hamburgerIcon:{
    marginLeft: 15,
    marginRight: 20,
    width: 20,
    height: 20,
    tintColor: '#FFF',
  },
  touchIcon:{marginRight: 20, width: 40, height: 40},
  titleText:{fontSize: 20, color: '#FFF', fontWeight: 'bold'},
  quantityView: {
    backgroundColor: '#FFFFFF',
    height: 25,
    width: 25,
    borderRadius: 12.5,
    borderColor: '#FFFFFF',
    borderWidth: 1,
    justifyContent: 'center',
    bottom: 30,
    position: 'absolute',
    right: 18,
  },
  priceStyle: {
    textAlign: 'center',
    color: '#0a0a0a',
    fontSize: 16,
  },
  addViewStyle: {
    marginTop: 10,
    width: '60%',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },
  plusMinusViewStyle2: {
    borderRadius: 20,
    marginTop: 10,
    width: '70%',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 30,
    paddingRight: 30,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },

  plusMinusViewStyle: {
    borderRadius: 20,
    marginTop: 10,
    width: '70%',
    height: '15%',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },
  plusView: {alignItems: 'center', justifyContent: 'center'},

  addTextStyle: {textAlign: 'center', fontSize: 16, color: '#2e8d0c'},
  plusTextStyle: {fontSize: 20, color: '#696969'},
  minusTextStyle: {fontSize: 20, color: '#696969'},
  rowViewStyle: {
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',

    margin: 20,
    flex: 1,
    width: '90%',
  },
  animateViewStyle: {
    flex: 1,
    width: '90%',
  },
  cartRowViewStyle: {
    flexDirection: 'row',

    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',

    margin: 20,
    flex: 1,
    width: '80%',
  },

  cartImageStyle: {
    marginLeft: 20,
    alignSelf: 'center',
    width: 100,
    height: 100,
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#ddd',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  cartPlusMinusViewStyle: {
    alignSelf: 'center',
    marginLeft: 20,
    marginTop: 10,
    width: '50%',
    paddingTop: 5,
    paddingBottom: 5,
    paddingLeft: 10,
    paddingRight: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
  },
});

export default styles;
